#!/usr/bin/env bash
#
# Start a tiny, single-node Slurm "cluster" inside this Codespace, so you can
# practise sbatch / squeue / scancel and see Nextflow submit jobs to a
# scheduler — without needing access to a real HPC.
#
#   bash hpc/start_slurm.sh
#
# Safe to re-run: if Slurm is already up it just tells you so. Re-run it after
# your Codespace restarts (the Slurm daemons don't survive a restart, and the
# machine's hostname can change).
#
# This is one machine *pretending* to be a cluster: the commands are the same
# as on a real HPC, but there's no real extra compute behind it.

set -euo pipefail

PARTITION=codespace
CONF=/etc/slurm/slurm.conf

as_root() { if [ "$(id -u)" -eq 0 ]; then "$@"; else sudo "$@"; fi; }
say()     { printf '\n\033[1m▶ %s\033[0m\n' "$*"; }

HOST=$(hostname -s)
NCPU=$(nproc)
# Leave ~1 GB for Nextflow itself and the rest of the Codespace.
MEM_MB=$(( $(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo) - 1024 ))
# Advertise twice the real CPUs, so a Nextflow "driver" job (1 CPU) and a
# pipeline step (up to 2 CPUs, the limit in codespaces.config) can run at the
# same time on a 2-core Codespace. Fine for practice; a real cluster wouldn't.
SLURM_CPUS=$(( NCPU * 2 ))

# --- Already running? ------------------------------------------------------
if pgrep -x slurmctld >/dev/null && pgrep -x slurmd >/dev/null \
   && grep -q "^NodeName=${HOST} " "$CONF" 2>/dev/null \
   && sinfo -h -o '%t' 2>/dev/null | grep -qE '^(idle|mix|alloc)'; then
    say "Slurm is already running on this Codespace 🎉"
    sinfo
    exit 0
fi

# --- 1. Install (first time only, ~1–2 minutes) ----------------------------
if ! command -v slurmctld >/dev/null || ! command -v munged >/dev/null; then
    say "Installing Slurm (first time only, takes a minute or two)…"
    as_root apt-get update -qq
    as_root env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
        slurmctld slurmd slurm-client munge >/dev/null
fi

# --- 2. Stop anything left over from before (e.g. an old hostname) ---------
as_root pkill -x slurmd    2>/dev/null || true
as_root pkill -x slurmctld 2>/dev/null || true
sleep 1

# --- 3. Munge: the authentication service Slurm uses -----------------------
say "Starting munge (Slurm's authentication service)…"
if ! as_root test -s /etc/munge/munge.key; then
    as_root mungekey --create --keyfile=/etc/munge/munge.key
fi
as_root chown munge:munge /etc/munge/munge.key
as_root chmod 400 /etc/munge/munge.key
as_root mkdir -p /run/munge /var/log/munge /var/lib/munge
as_root chown munge:munge /run/munge /var/log/munge /var/lib/munge
if ! pgrep -x munged >/dev/null; then
    as_root runuser -u munge -- /usr/sbin/munged
fi

# --- 4. Write the Slurm config for *this* machine --------------------------
say "Configuring a one-node cluster: ${HOST} (${SLURM_CPUS} CPUs, ${MEM_MB} MB)…"
as_root mkdir -p /etc/slurm /var/spool/slurmctld /var/spool/slurmd /var/log/slurm
as_root tee "$CONF" >/dev/null <<EOF
# Generated by hpc/start_slurm.sh — a single-node practice cluster.
ClusterName=codespace
SlurmctldHost=${HOST}
AuthType=auth/munge
SlurmUser=root
StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd
SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log

# No cgroups inside a Codespace container: track and launch jobs simply.
ProctrackType=proctrack/linuxproc
TaskPlugin=task/none
JobAcctGatherType=jobacct_gather/none
AccountingStorageType=accounting_storage/none
MpiDefault=none
MailProg=/bin/true

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core
ReturnToService=2
# Trust the CPU count below, even though it's more than the real cores.
SlurmdParameters=config_overrides

NodeName=${HOST} CPUs=${SLURM_CPUS} RealMemory=${MEM_MB} State=UNKNOWN
PartitionName=${PARTITION} Nodes=ALL Default=YES MaxTime=INFINITE State=UP
EOF
# Slurm won't start without a cgroup.conf present, even when not using cgroups.
echo "CgroupPlugin=disabled" | as_root tee /etc/slurm/cgroup.conf >/dev/null

# --- 5. Start the controller and the compute-node daemon -------------------
say "Starting the Slurm controller and compute node…"
as_root slurmctld -c    # -c: start with a clean slate (no jobs from before)
as_root slurmd

for _ in $(seq 1 30); do
    state=$(sinfo -h -o '%t' 2>/dev/null || true)
    case "$state" in
        idle*|mix*|alloc*) break ;;
        down*|drain*)      as_root scontrol update nodename="$HOST" state=resume 2>/dev/null || true ;;
    esac
    sleep 1
done

if ! sinfo -h -o '%t' 2>/dev/null | grep -qE '^(idle|mix|alloc)'; then
    echo "❌ Slurm didn't come up. The logs are in /var/log/slurm/ — e.g.:" >&2
    echo "   sudo tail /var/log/slurm/slurmctld.log /var/log/slurm/slurmd.log" >&2
    exit 1
fi

say "Your practice Slurm cluster is ready 🎉"
sinfo
echo
echo "Try:  sbatch --wrap 'hostname; sleep 30'   then   squeue"
